### PR TITLE
Hardcore makefile cleanups

### PR DESCRIPTION
**Pull request by mrnuke**

### CODE REVIEW

**Comment by mithro** [comment]
Hi @mrnuke ,

Thanks for contributing to this project. What is your interest in this project? It looks like you are trying to make it compatible with building on Fedora?

There are a couple of things I need changed before I could merge this pull request;
 * Please don't remove the debian folder. If you need something for Fedora, feel free to add an equivalent directory.
 * There are actually multiple assemblers which sdcc uses, can you keep the ability to override the assembler binary.
 * Can you keep the boot / ref targets?

Thanks for your efforts!

Tim 'mithro' Ansell

**Comment by mrnuke** [comment]
We have a lot of Digilent JTAG-USB cables at some place I work, and I'd like to get them working with openocd and linux.

> If you need something for Fedora, feel free to add an equivalent directory.

I'll keep the Fedora stufff in a separate branch. I don't want to end up with a thousand rules for a thousand distros.

> There are actually multiple assemblers which sdcc uses, can you keep the ability to override the assembler binary.

I didn't remove that ability.

**Comment by mithro** [comment]
@mrnuke Which Digilent JTAG-USB cables do you mean? Most of them *wont* work with this firmware as they are based around FTDI chips rather than the FX2 (however they will work with OpenOCD using the FTDI driver).

**Comment by mrnuke** [comment]
[This bastard](http://store.digilentinc.com/jtag-usb-cable/) uses a Cypress FX2

**Comment by mithro** [comment]
Have you gotten the ixo-usb-jtag working with this board?

**Comment by mrnuke** [comment]
I got it pushing some data to a shift register, but I need to test on a real JTAG target before I submit a PR.

**Pull request merged**
